# Generated by Django 3.2.7 on 2021-11-28 15:30

from django.db import migrations, models
import saprgramapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('saprgramapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='user_photo',
            field=models.ImageField(upload_to=saprgramapp.models.user_directory_path),
        ),
    ]
