# Generated by Django 3.2.7 on 2021-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, default='18'),
        ),
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
